# Generated by Django 2.1.5 on 2019-01-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190129_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Classroom',
            new_name='classroom',
        ),
    ]
