# Generated by Django 2.1.5 on 2019-01-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190131_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Classroom'),
        ),
    ]
