# Generated by Django 2.1.5 on 2019-01-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190131_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='newpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.NewPost'),
        ),
    ]
