# Generated by Django 2.1.5 on 2019-02-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190131_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='student',
        ),
        migrations.AddField(
            model_name='students',
            name='newpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.NewPost'),
        ),
    ]
